apiVersion: v1
kind: ConfigMap
data:
  MEDIAWIKI_SERVER: {{ .Values.configMap.server  }}
  MEDIAWIKI_SITENAME: {{ .Values.configMap.siteName }}
  MEDIAWIKI_DB_HOST: {{ .Values.configMap.dbHost }}
  MEDIAWIKI_DB_NAME: {{ .Values.configMap.wikiDb }}
  MEDIAWIKI_DEFAULT_SKIN: {{ .Values.configMap.defaultSkin }}
metadata:
  labels:
    app: {{ .Values.deployment.name }}
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
