apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistentVolume.accessModes }}
  persistentVolumeReclaimPolicy:
  storageClassName: {{ .Values.storageClass.name }}
  mountOptions:
    - tls
  csi:
    driver: {{ .Values.storageClass.provisioner }}
    volumeHandle: {{ .Values.persistentVolume.volumeHandle }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.persistentVolume.accessModes }}
  storageClassName: {{ .Values.storageClass.name }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
