apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MEDIAWIKI_DB_USER: {{ .Values.secrets.dbUser }}
  MEDIAWIKI_DB_PASSWORD: {{ .Values.secrets.dbPass }}
