apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.name }}
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      protocol: {{ .Values.service.protocol }}
      port:  {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
